### ISSUE TITLE
DirectoryNotFoundException: C:\Users\VssAdministrator\.nuget\packages\telerik.ui.for.blazor\1.2.0\staticwebassets\

### ISSUE THREAD

**Issue by marcelgoldstein** [marcelgoldstein/MiniatureGolf#54]
An error occurred while starting the application.
DirectoryNotFoundException: C:\Users\VssAdministrator\.nuget\packages\telerik.ui.for.blazor\1.2.0\staticwebassets\

Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(string root, ExclusionFilters filters)

    DirectoryNotFoundException: C:\Users\VssAdministrator\.nuget\packages\telerik.ui.for.blazor\1.2.0\staticwebassets\
        Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(string root, ExclusionFilters filters)
        Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(string root)
        Microsoft.AspNetCore.StaticWebAssetsFileProvider..ctor(string pathPrefix, string contentRoot)
        Microsoft.AspNetCore.StaticWebAssetsLoader+<>c.<UseStaticWebAssetsCore>b__2_0(ContentRootMapping cr)
        System.Linq.Enumerable+SelectEnumerableIterator<TSource, TResult>.MoveNext()
        System.Linq.Enumerable.OfTypeIterator<TResult>(IEnumerable source)+MoveNext()
        System.Collections.Generic.List<T>..ctor(IEnumerable<T> collection)
        System.Linq.Enumerable.ToList<TSource>(IEnumerable<TSource> source)
        Microsoft.AspNetCore.StaticWebAssetsLoader.UseStaticWebAssetsCore(IWebHostEnvironment environment, Stream manifest)
        Microsoft.AspNetCore.StaticWebAssetsLoader.UseStaticWebAssets(IWebHostEnvironment environment)
        Microsoft.AspNetCore.WebHost+<>c.<ConfigureWebDefaults>b__9_0(WebHostBuilderContext ctx, IConfigurationBuilder cb)
        Microsoft.AspNetCore.Hosting.Internal.GenericWebHostBuilder+<>c__DisplayClass8_0.<ConfigureAppConfiguration>b__0(HostBuilderContext context, IConfigurationBuilder builder)
        Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
        Microsoft.Extensions.Hosting.HostBuilder.Build()
        MiniatureGolf.Program.Main(string[] args) in Program.cs

    System.IO.DirectoryNotFoundException: C:\Users\VssAdministrator\.nuget\packages\telerik.ui.for.blazor\1.2.0\staticwebassets\

       at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)

       at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)

       at Microsoft.AspNetCore.StaticWebAssetsFileProvider..ctor(String pathPrefix, String contentRoot)

       at Microsoft.AspNetCore.StaticWebAssetsLoader.<>c.<UseStaticWebAssetsCore>b__2_0(ContentRootMapping cr)

       at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()

       at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable source)+MoveNext()

       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

       at Microsoft.AspNetCore.StaticWebAssetsLoader.UseStaticWebAssetsCore(IWebHostEnvironment environment, Stream manifest)

       at Microsoft.AspNetCore.StaticWebAssetsLoader.UseStaticWebAssets(IWebHostEnvironment environment)

       at Microsoft.AspNetCore.WebHost.<>c.<ConfigureWebDefaults>b__9_0(WebHostBuilderContext ctx, IConfigurationBuilder cb)

       at Microsoft.AspNetCore.Hosting.Internal.GenericWebHostBuilder.<>c__DisplayClass8_0.<ConfigureAppConfiguration>b__0(HostBuilderContext context, IConfigurationBuilder builder)

       at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()

       at Microsoft.Extensions.Hosting.HostBuilder.Build()

       at MiniatureGolf.Program.Main(String[] args) in d:\a\1\s\MiniatureGolf\Program.cs:line 11

.NET Core 3.0.0-preview6-27804-01 X86 v4.0.0.0    |   Microsoft.AspNetCore.Hosting version 3.0.0-preview6.19307.2    |    Microsoft Windows 10.0.14393    |   Need help?

**Comment by marcelgoldstein** [comment]
there same kind of a bug with the "static assets" included in the nuget package, so for the .js file it should be switched back to the CDN versiion.

**Comment by marcelgoldstein** [comment]
this is not solved with using the CDN. so the upgrade to telerik ui for blazor 1.2.0 needs to be undone. this will be done #51 and also will be redone later when the bug hopefully got resolved.
